spring.application.name=PaymentsTKafka
#Server configuration

server.port=8080

#Spring Kafka Configuration

spring.kafka.bootstrap-servers=localhost:9092

#Consumer Configuration

# Kafka Consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Required for JSON Deserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*


#Producer Configuration

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#Custom Application Topics

app.topics.payment-initiated=payment-initiated
app.topics.payment-validated=payment-validated
app.topics.payment-fraud-check=payment-fraud-check
app.topics.payment-authorized=payment-authorized
app.topics.payment-declined=payment-declined
app.topics.payment-notifications=payment-notifications
app.topics.payment-dlq=payment-dlq